##### Packages #####
library(Seurat)
library(dplyr)
library(tidyr)
library(SeuratWrappers)
library(Matrix)
library(ggplot2)
library(ggbreak)
library(stats)
library(DropletUtils)
library(devtools)
library(patchwork)
library(ggpubr)
library(pheatmap)
library(scCDC)
library(decontX)
library(SoupX)
library(ggVennDiagram)
library(SCDC)
library(scDblFinder)
library(DoubletFinder)
library(mclust)
library(slingshot)
library(RColorBrewer)

library(scCDC)

